"""Export service for converting itineraries to various formats."""

from typing import Any, Dict, Optional
from datetime import datetime

from app.models.itinerary import Itinerary
from app.schemas.itinerary import ItineraryProposal, ItineraryDay, Activity


def format_activity_markdown(activity: Activity) -> str:
    """Format a single activity as markdown."""
    lines = [f"- **{activity.time}** - {activity.name}"]
    lines.append(f"  - {activity.description}")
    lines.append(f"  - Duration: {activity.duration}")

    if activity.location:
        lines.append(f"  - Location: {activity.location}")
    if activity.cost_estimate:
        lines.append(f"  - Cost: {activity.cost_estimate}")
    if activity.booking_required:
        lines.append("  - *Booking required*")

    return "\n".join(lines)


def format_day_markdown(day: ItineraryDay) -> str:
    """Format a single day as markdown."""
    lines = [
        f"### Day {day.day_number}: {day.title}",
        f"**Date:** {day.date}",
        f"**Location:** {day.location}",
        "",
        "#### Activities",
    ]

    for activity in day.activities:
        lines.append(format_activity_markdown(activity))
        lines.append("")

    if day.accommodation:
        lines.append("#### Accommodation")
        lines.append(f"- **{day.accommodation.name}** ({day.accommodation.style})")
        lines.append(f"  - Area: {day.accommodation.area}")
        lines.append(f"  - Price: {day.accommodation.price_range}")
        if day.accommodation.notes:
            lines.append(f"  - Notes: {day.accommodation.notes}")
        lines.append("")

    if day.notes:
        lines.append(f"> {day.notes}")
        lines.append("")

    return "\n".join(lines)


def format_proposal_markdown(proposal: ItineraryProposal, include_header: bool = True) -> str:
    """Format a single proposal as markdown."""
    lines = []

    if include_header:
        lines.append(f"## {proposal.title}")
        lines.append("")
        lines.append(proposal.summary)
        lines.append("")
        lines.append(f"**Estimated Budget:** {proposal.total_budget_estimate}")
        lines.append("")

    if proposal.highlights:
        lines.append("### Highlights")
        for highlight in proposal.highlights:
            lines.append(f"- {highlight}")
        lines.append("")

    lines.append("### Day-by-Day Itinerary")
    lines.append("")

    for day in proposal.days:
        lines.append(format_day_markdown(day))

    if proposal.caveats:
        lines.append("### Things to Consider")
        for caveat in proposal.caveats:
            lines.append(f"- {caveat}")
        lines.append("")

    return "\n".join(lines)


def itinerary_to_markdown(itinerary: Itinerary, proposal_id: Optional[str] = None) -> str:
    """
    Convert itinerary to markdown format.

    If proposal_id is provided, exports only that proposal.
    If selected_proposal_id is set and no proposal_id provided, exports selected.
    Otherwise exports all proposals.
    """
    proposals = itinerary.proposals

    # Determine which proposal(s) to export
    target_proposal_id = proposal_id or itinerary.selected_proposal_id

    if target_proposal_id:
        # Export single proposal
        proposal = next((p for p in proposals if p.id == target_proposal_id), None)
        if not proposal:
            proposal = proposals[0]  # Fallback to first
        proposals_to_export = [proposal]
    else:
        proposals_to_export = proposals

    # Build markdown document
    lines = [
        f"# {itinerary.destination} Travel Itinerary",
        "",
        f"**Dates:** {itinerary.start_date} to {itinerary.end_date}",
        f"**Travelers:** {itinerary.num_travelers}",
        f"**Generated:** {itinerary.created_at.strftime('%Y-%m-%d')}",
        "",
        "---",
        "",
    ]

    for proposal in proposals_to_export:
        lines.append(format_proposal_markdown(proposal))
        lines.append("---")
        lines.append("")

    lines.append("*Generated by Wanderlust*")

    return "\n".join(lines)


def itinerary_to_json(itinerary: Itinerary, proposal_id: Optional[str] = None) -> Dict[str, Any]:
    """
    Convert itinerary to clean JSON format.

    If proposal_id is provided, exports only that proposal.
    If selected_proposal_id is set and no proposal_id provided, exports selected.
    Otherwise exports all proposals.
    """
    proposals = itinerary.proposals

    # Determine which proposal(s) to export
    target_proposal_id = proposal_id or itinerary.selected_proposal_id

    if target_proposal_id:
        proposal = next((p for p in proposals if p.id == target_proposal_id), None)
        if not proposal:
            proposal = proposals[0]
        proposals_to_export = [proposal]
    else:
        proposals_to_export = proposals

    return {
        "destination": itinerary.destination,
        "start_date": itinerary.start_date,
        "end_date": itinerary.end_date,
        "num_travelers": itinerary.num_travelers,
        "selected_proposal_id": itinerary.selected_proposal_id,
        "generated_at": itinerary.created_at.isoformat(),
        "proposals": [p.model_dump() for p in proposals_to_export],
        "metadata": {
            "version": "1.0",
            "generator": "Wanderlust",
            "export_date": datetime.utcnow().isoformat(),
        }
    }
